<?php

namespace ApiBundle\Repository;

/**
 * AttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AttachementRepository extends \Doctrine\ORM\EntityRepository
{
}
