<?php

namespace ApiBundle\Repository;

/**
 * ImageAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageAttachementRepository extends \Doctrine\ORM\EntityRepository
{
}
