<?php

namespace ApiBundle\Repository;

/**
 * MessageAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MessageAttachementRepository extends \Doctrine\ORM\EntityRepository
{
}
