<?php

namespace ApiBundle\Repository;

/**
 * VideoAttachementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VideoAttachementRepository extends \Doctrine\ORM\EntityRepository
{
}
